name: CI
run-name: CI for ${{github.ref_name}}
on:
  pull_request: { branches: [ master ] }
  push:
    branches: [ master ]
    tags: [ .* ]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run flake check
        run: nix flake check
